resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: DestaceyBashCalcRepo 
    type: github
    endpoint: GitHub-parallel
    name: destacey/bashCalc
# The name used to reference this repository in the checkout step
  - repository: DestaceyWindowsBatchRepo
    type: github
    endpoint: GitHub-parallel
    name: destacey/winBatch

trigger:
- master

stages:
#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts
    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
